# Site settings
title: Bart Jaskulski
email: bjaskulski@protonmail.com
url: "https://bartjaskulski.com/"

# Build settings
markdown: kramdown
permalink: /blog/:title
kramdown:
  auto_ids          : false
#excerpt_separator: <!--more-->

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bin
  - paths.js
  - postcss.config.js
